title: My Own Library # name of the site
author: Alejandro Rodiño # name of site's author
email: arodino@fen.uchile.cl # email of site's author
url: "ale_blog" # root address of the site
description: > # description of the site (multiple lines allowed)
  ================================================================================================
  <p style="margin-left:2.5em">This repository was created by me so i could keep track of papers, classes, or other useful things that i
  thought were interesting and it would be nice to have them available at any point in time.  <br>
   <br>
  I'm a 4th year student in Economics at the University of Chile.<br>
  Currently in the pursue of learning about Behavioural Economics, Economics of Education, Health Economics and also i like programming.

  </p>
  ================================================================================================
permalink: /:slug.html

favicon: "./logo.png" # relative path to site's favicon
# goat_counter: "yoursitename" # put your GoatCounter name if you want to use GoatCounter analytics

theme: riggraz/no-style-please # if you are using GitHub Pages, change it to remote_theme: riggraz/no-style-please

theme_config:
  appearance: "dark" # can be "light", "dark" or "auto"
  back_home_text: "Atráss" # customize text for homepage link in post layout
  date_format: "%Y-%m-%d" # customize how date is formatted
  show_description: true # show blog description in home page
  show_email: true #
  show_author: true #
sass:
  style: :compressed

plugins:
  - jekyll-feed
  - jekyll-seo-tag
